"""新增 movies 表 poster_path 欄位

Revision ID: 4583575128f9
Revises: 5616499821b9
Create Date: 2021-12-28 22:42:32.176772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4583575128f9'
down_revision = '5616499821b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_path', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster_path')
    # ### end Alembic commands ###
